### ISSUE TITLE
Mame Mix Imgs from Screenscraper.fr

### ISSUE THREAD

**Issue by stigzler** [sselph/scraper#208] opened 2018-01-14 19:54 UTC
Firstly, awesome little app. Saved me a ton of coding! Got it up and running great for non-mame systems. Using the following cmd line:

`scraper -rom_dir "\\RECALBOX\share\roms\atari2600" -console_src "ss,gdb,ovgdb" -console_img "mix3,mix4,3b,b,s,l,f,a"  `

(mix3,mix4 found in a post somewhere)

I'm designing a windows desktop app for managing Recalbox installations (roms, scraping etc). When I scrape mame from recalbox itself (with screenscraper as the source) I get 'composite' images of snap, logo and box. 

However, when I try to scrape via scraper.exe using:

`scraper -rom_dir "\\RECALBOX\share\roms\mame" -mame -mame_src "ss,mamedb,gdb" -mame_img mix4,mix3,t,s,m,c`

All i get is snaps. 

Any ideas how to get the mame composite images?

P.S. I notice I still get things from screenscraper even when I don't use my username and password for that site - is this right?

**Comment by paradadf** [comment] 2018-01-14 21:00
Sort of duplicate of: https://github.com/sselph/scraper/issues/189

What you get from the ES scraper within recalbox are new media types.
And no, you don’t need to use credenrials to scrape wirh ss, but it is highly recommended because by high demand, unregistered users are blocked.

**Closed** 2018-01-18 06:15 UTC
