### ISSUE TITLE
Getting same game result - ZX Spectrum PSX scraping

### ISSUE THREAD

**Issue by nickdj** [sselph/scraper#216] opened 2018-02-05 09:27 UTC
Hiya.  I'm trying to scrape using the source 'ss' (screenscraper) but notice I keep seeing the same results.  When trying to scrape PSX nearly all results come back as the PSP game ".hack/sign" and this also happens on zxspectrum. It happens in others but not so much.  If I try using the source "gdb" I don't get any results with zxspectrum and it looks like its only scraping a fraction of files. 

I'm using my own batch script and it all looks good.  I can scrape from EmulationStation (PC) which uses GamessDB which works but painfully slow and misses quite a few results.  Does ScreenScraper default to this result if no details are found?

**Comment by nickdj** [comment] 2018-02-05 10:56
If it helps, this is the result I get from an incorrectly matched game:

-<game source="screenscraper.fr" id="65505">
<path>./1 Line Othello (2007)(Digital Prawn).z80</path>
<name>.hack-Link</name>
<desc>The first game in the .hack series for PSP (and the planned final game for the franchise), .hack//LINK logs player into a new version of its virtual landscape called The World R:X (the &quot;R&quot; stands for &quot;Revision&quot;). Set 10 years after the last .Hack, players take control of Tokio Kuryu, a second year junior-high student. Presented through manga-style visuals, the game's story promises to clear up the mysteries from past entries. Over 100 characters from past .hack games, anime, manga, and books will make an appearance. Gameplay promises to retain the basics of past titles, with players facing off in battle against enemies as they explore dungeons. The difference here is that you move around in a party of two, with the CPU-controlling the other character. The game will include 33 such CPU-controlled characters. For the PSP game, the battle system has been changed to a more action-heavy combat system.</desc>
<image>~/.emulationstation/downloaded_images/zxspectrum/1 Line Othello (2007)(Digital Prawn)-image.png</image>
<rating>0.85</rating>
<releasedate>20100304T000000</releasedate>
<developer>Bandai Namco</developer>
<publisher>CyberConnect2</publisher>
<genre>Role playing games</genre>
</game>

If this is a default result for an unmatched rom, is there a way to stop it saving the results?

**Comment by sselph** [comment] 2018-02-13 02:01
Dupe of #214

**Closed** 2018-02-13 02:01 UTC
